#!/bin/bash

/home/matthewwang16czap/miniconda3/envs/llava/bin/deepspeed ./C3L/scripts/train_sdpa.py \
    --lora_enable True --lora_r 16 --lora_alpha 64 --mm_projector_lr 5e-6 \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path /home/matthewwang16czap/models/llava-v1.5-7b \
    --version v1 \
    --data_path ./C3L/data/filtered_questions.json \
    --image_folder /home/matthewwang16czap/fiftyone/coco-2014/train/data \
    --vision_tower /home/matthewwang16czap/models/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --tf32 False \
    --fp16 False \
    --output_dir ./checkpoints/llava-v1.5-7b-finetuned-lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 5e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --model_max_length 1024 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to none